spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ql_csvc?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      pool-name: TestHikariCP  # ??t t?n cho pool c?a HikariCP

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true  # ??nh d?ng SQL ?? d? ??c

    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 20MB

  server:
    port: 8080

