spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ql_csvc_utc_sql?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      pool-name: TestHikariCP

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update   # update | create | create-drop | validate | none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: trueu

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080
